version: '3'
services:
  subscriber:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -u src/workers/subscriber.py
    working_dir: /src
    environment: 
      - POSTGRES_HOST=10.107.176.3
      - POSTGRES_PORT=5432
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=miso4204
      - POSTGRES_DB=miso4204db